### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by balasankarc** [xflr6/graphviz#18]
When I run nosetests, I am getting two failures. Here are the logs

```
..........spam:E: invalid option "T"
spam:I: usage is "spam [-vCeghlprx] [-b bctf] [-f error_file] [-c catalog_sysid] [-D dir] [-a link_type] [-A arch] [-E max_errors] [-i entity] [-w warning_type] [-m omittag|shortref|net|emptytag|unclosed|attname|attvalue|attspec|current|shorttag|rank|reserved] [-o entity_name] sysid..."
Fspam:E: invalid option "T"
spam:I: usage is "spam [-vCeghlprx] [-b bctf] [-f error_file] [-c catalog_sysid] [-D dir] [-a link_type] [-A arch] [-E max_errors] [-i entity] [-w warning_type] [-m omittag|shortref|net|emptytag|unclosed|attname|attvalue|attspec|current|shorttag|rank|reserved] [-o entity_name] sysid..."
F................
======================================================================
FAIL: test_pipe (test_files.TestNoent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/balasankarc/git/graphviz/tests/test_files.py", line 50, in test_pipe
    self.file.pipe()
AssertionError: RuntimeError not raised

======================================================================
FAIL: test_render (test_files.TestNoent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/balasankarc/git/graphviz/tests/test_files.py", line 54, in test_render
    self.file.render()
AssertionError: RuntimeError not raised

Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
graphviz.py               9      0   100%   
graphviz/_compat.py       2      0   100%   
graphviz/dot.py          71      0   100%   
graphviz/files.py       124     14    89%   163-165, 191, 220-222, 231, 246-248, 262, 273, 278
graphviz/lang.py         40      0   100%   
graphviz/tools.py        18      1    94%   38
---------------------------------------------------
TOTAL                   264     15    94%   
----------------------------------------------------------------------
Ran 28 tests in 0.433s

FAILED (failures=2)

```

**Comment by xflr6** [comment]
Thanks for reporting.

Tests the exception handling in `pipe()` and `render()`.
Tries to provoke `ENOENT` by calling a non-existent executable with the name `spam` which happens to exist on your (and potentially other users) system. Switch to a name with higher entropy?

**Comment by balasankarc** [comment]
Yes. `spam` is an SGML markup stream editor that may be installed in many users' systems. It would be better to use a non-generic name.

**Comment by balasankarc** [comment]
BTW, I am trying to package graphviz package for Debian.
