### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by niannianQAQ** [xflr6/graphviz#222]
Hi everyone,

I've installed graphviz0.18 in Pycharm and graphviz-install-2.50.0-win64 in my computer, and the pm4py version is 2.2.3 and the python version is 3.9.
 I receive this message error:
```
Traceback (most recent call last):
  File "D:\chatbot-process-mining\chatbot_evaluation.py", line 6, in <module>
    import pm4py
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\__init__.py", line 20, in <module>
    from pm4py import util, objects, statistics, algo, visualization
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\visualization\__init__.py", line 21, in <module>
    from pm4py.visualization import common, dfg, petrinet, process_tree, transition_system, decisiontree, align_table, \
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\visualization\common\__init__.py", line 17, in <module>
    from pm4py.visualization.common import save, utils, gview, visualizer
  File "D:\chatbot-process-mining\venv\lib\site-packages\pm4py\visualization\common\gview.py", line 21, in <module>
    from graphviz.dot import Digraph
ImportError: cannot import name 'Digraph' from 'graphviz.dot' (D:\chatbot-process-mining\venv\lib\site-packages\graphviz\dot.py)
```
gview.py line 21:
```
19 from pm4py.util import vis_utils, constants
20 from io import BytesIO
21 from graphviz.dot import Digraph
```

**Comment by xflr6** [comment]
>  `import pm4py`

IIUC you are trying to report an error in https://pypi.org/project/pm4py (not in this package, `graphviz`, which seems to be used as a dependency by `pm4py`).

You are probably looking for https://github.com/pm4py/pm4py-core/issues (e.g. https://github.com/pm4py/pm4py-core/issues/282 seems to describe the same issue).

From a quick look you seem to be using an older version of that package, that had a bug relying on non-public API in `graphviz`. Seems to have been fixed in https://github.com/pm4py/pm4py-core/commit/01d3dc44861ab0cf6167ec4d86576b64528eb48d.

Hope that helps, closing.
