### ISSUE TITLE
Strange escaping of `::`, generating DOT syntax error

### ISSUE THREAD

**Issue by thomas-riccardi** [xflr6/graphviz#53]
```python
from graphviz import Digraph

print("Bug 1: strange generated DOT source")
dot = Digraph(filename='bug-escaping-1.dot', format='png')

n1 = "A"
n2 = "::"
dot.node(n1)
dot.node(n2)
dot.edge(n1, n2)

print(dot.source)
dot.render()


print("Bug 2: crash")
dot = Digraph(filename='bug-escaping-2.dot', format='png')

n1 = "A"
n2 = "'B::C'"
dot.node(n1)
dot.node(n2)
dot.edge(n1, n2)

print(dot.source)
dot.render()
```

Result:
```
$ python3 bug-escaping.py 
Bug 1: strange generated DOT source
digraph {
        A
        "::"
        A -> "":""
}
Bug 2: crash
digraph {
        A
        "'B::C'"
        A -> "'B":"":C'
}
Error: bug-escaping-2.dot: syntax error in line 4 near '''
Traceback (most recent call last):
  File "bug-escaping.py", line 26, in <module>
    dot.render()
  File "/home/thomas/.local/lib/python3.5/site-packages/graphviz/files.py", line 176, in render
    rendered = backend.render(self._engine, self._format, filepath)
  File "/home/thomas/.local/lib/python3.5/site-packages/graphviz/backend.py", line 124, in render
    subprocess.check_call(args, startupinfo=STARTUPINFO, stderr=stderr)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['dot', '-Tpng', '-O', 'bug-escaping-2.dot']' returned non-zero exit status 1
```

Info:
- graphviz 0.8.3
- Python 3.5.2

**Comment by thomas-riccardi** [comment]
Thanks @xflr6 for the workaround, I'll use that in the meantime.

**Comment by mgoral** [comment]
I just encountered this issue when creating a graph with some C++ modifiers in it (`::` is used as a namespace separator in C++). I'm not very familiar with DOT language so the way how graphviz treated colons was very surprising to me. I'm fine with pre-processing nodes though and it's not very hard to e.g. assign a number to each unique node identifier.

I think that situation would be better if special meaning of colons (and possibly other characters) was documented better, especially that Python library hides the details of DOT language behind a nice and clean API.

**Comment by xflr6** [comment]
Thanks. I agree: let's try to better document the current behaviour (maybe you want to help with this?).

**Comment by mgoral** [comment]
I'll try my best, but as I said I'm not very familiar with DOT language nor with implementation of your library, so I don't want to promise anything. :)

**Comment by bayersglassey-zesty** [comment]
It might be nice if port and compass were kwargs, as opposed to things parsed out of the name; 
or even if name was allowed to be any of: 'id', ('id,), ('id', 'port'), or ('id', 'port', 'compass').

(Bringing this suggestion into this issue from here: https://github.com/xflr6/graphviz/issues/168#issuecomment-1100677538)

**Comment by bayersglassey-zesty** [comment]
Having looked at the code a bit and thought about the different ways `node()` and `edge()` do their quoting, I actually think a `NodeID` class would work quite well, instead of tuples. It's a bit more explicit, and allows you to pass "fully-qualified" node IDs (including port + compass) to `node()`, which wasn't previously possible. (And is also totally useless, because node statements ignore ports and compasses. But it's nice to be consistent.)
Here's a draft PR for that: https://github.com/xflr6/graphviz/pull/169
